### PR TITLE
update rails and bower components

### PR DESCRIPTION
**Pull request by barberj**
Update to latest and greatest ruby, rails and angular.

### CODE REVIEW

**Comment by barberj** [comment]
Was hoping to reproduce my error in this repo, but alas I failed...

**Comment by barberj** [comment]
What do you think?

**Comment by barberj** [comment]
:wave:

**Comment by sb8244** [comment]
I thought you only wanted it bumped because of the error you couldn't reproduce

**Comment by sb8244** [comment]
Just pulled down and it looks good. Thanks for updating deps

**Comment by barberj** [comment]
Originally was to reproduce. Tutorials on dated tools loose value though which is why I felt inclined to pr

Thanks for merging.

**Pull request merged**
